locations = ['zaire', 'ghana', 'nigeria', 'togo', 'argentina', 'brazil']
print(locations)
sort_location = sorted(locations)
print(sort_location)
print(locations)
reverse_sorted = sorted(locations, reverse=True)
print(reverse_sorted)
print(locations)
print('reverse')
locations.reverse()
print(locations)
print('back to original')
locations.reverse()
print(locations)
print('sorted A-Z')
locations.sort()
print(locations)
print('sorted Z - A')
locations.sort(reverse=True)
print(locations)